export const tipoDocumentos = [
    { value: '93', label: 'Acta nacimiento' },
    { value: '87', label: 'CDI' },
    { value: '95', label: 'CI Bs. As. RNP' },
    { value: '1', label: 'CI Buenos Aires' },
    { value: '16', label: 'CI Chaco' },
    { value: '17', label: 'CI Chubut' },
    { value: '91', label: 'CI extranjera' },
    { value: '18', label: 'CI Formosa' },
    { value: '8', label: 'CI La Rioja' },
    { value: '7', label: 'CI Mendoza' },
    { value: '19', label: 'CI Misiones' },
    { value: '20', label: 'CI Neuquén' },
    { value: '0', label: 'CI Policía Federal' },
    { value: '9', label: 'CI Salta' },
    { value: '10', label: 'CI San Juan' },
    { value: '12', label: 'CI San Luis' },
    { value: '11', label: 'CI Santa Fe' },
    { value: '13', label: 'CI Sgo.del Estero' },
    { value: '14', label: 'CI Tucumán' },
    { value: '86', label: 'CUIL' },
    { value: '80', label: 'CUIT' },
    { value: '70', label: 'CUIT País' },
    { value: '96', label: 'DNI' },
    { value: '92', label: 'En trámite' },
    { value: '90', label: 'LC' },
    { value: '89', label: 'LE' },
    { value: '94', label: 'Pasaporte' }
];