export const types = {

    authIngresarUsuario: '[auth] Ingresar usuario',
    authSalirUsuario: '[auth] Salir usuario',
    authFinalizarComprobacion: '[auth] Finalizar comprobacion',
    authSetFormSeguridad: '[auth] Set form seguridad',
    authRemoverFormSeguridad: '[auth] Remover form seguridad',

    uiSetError: '[ui] Set error',
    uiRemoveError: '[ui] Remove error',
    uiStartLoading: '[ui] Start loading',
    uiFinishLoading: '[ui] Finish loading',
    uiShowModal: '[ui] Show modal',
    uiCloseModal: '[ui] Close modal',
    uiSetRedirect: '[ui] Set redirect',
    uiRemoveRedirect: '[ui] Remove redirect',

    personaAgregarPersona: '[persona] Persona nueva agregada',
    personaSetPersonaActiva: '[persona] Set persona activa',
    personaRemoverPersonaActiva: '[persona] Persona activa removida',
    personaActualizarPersona: '[persona] Persona actualizada',
    personaEliminarPersona: '[persona] Persona eliminada',
    personaCargarPersonas: '[persona] Personas cargada',
    personaAgregarFiltro: '[persona] Filtro agregado',
    personaRemoverFiltro: '[persona] Filtro removido',
    personaRemoverLosFiltro: '[persona] Filtros removidos',

    grillaSetPaginaActual: '[grilla] Set pagina actual',
    grillaSetRegistrosPorPagina: '[grilla] Set registros por pagina',
    grillaSetDatosGrilla: '[grilla] Set datos grilla',

    cuitCargarCuits: '[cuit] Cuits cargados',
    cuitSetCuitActivo: '[cuit] Set cuit activo',
    cuitRemoverCuitActivo: '[cuit] Cuit activo removido',
    cuitAgregarCuit: '[cuit] Cuit nuevo agregado',
    cuitActualizarCuit: '[cuit] Cuit actualizado',
    cuitEliminarCuit: '[cuit] Cuit eliminado',
    cuitSetUnidadNegocioActivo: '[cuit] Set unidad de negocio activo',
    cuitRemoverUnidadNegocioActivo: '[cuit] Unidad de negocio activo removido',
    cuitEliminarUnidadNegocio: '[cuit] Unidad de negocio eliminado',
    cuitSetPuntoVentaActivo: '[cuit] Set punto de venta activo',
    cuitRemoverPuntoVentaActivo: '[cuit] Punto de venta activo removido',
};